### ISSUE TITLE
Error when loading file 

### ISSUE THREAD

**Issue by DejanDexa** [DejanDexa/TodoList#4]
Error at application startup

java.io.StreamCorruptedException: invalid stream header: 6E616D65
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:877)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:350)
	at Main.readFromFile(Main.java:107)
	at Main.startTodoList(Main.java:222)
	at Main.main(Main.java:23)

**Comment by DejanDexa** [comment]
Duplicate
