### ISSUE TITLE
Error while saving file

### ISSUE THREAD

**Issue by DejanDexa** [DejanDexa/TodoList#8]
Error saving to file
java.io.NotSerializableException: Model.ToDoList
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at ToDoListController.saveToFile(ToDoListController.java:99)
	at ToDoListController.performActions(ToDoListController.java:129)
	at Main.main(Main.java:26)

**Comment by DejanDexa** [comment]
Fixed with ControllerRefactoring
